// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package dao

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID     uuid.UUID
	Name       string
	Email      string
	Password   string
	CreatedAt  time.Time
	ModifiedAt time.Time
}
